/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Solution_Two
{
    class Program
    {
        static void Main(string[] args)
        {
            int firstTerm = 0;
            int secondTerm = 1;
            int fibonacciTerm = 1;
            int total = 0;

            for (fibonacciTerm = 1; fibonacciTerm <= 4000000;
                fibonacciTerm = firstTerm + secondTerm)
            {
                Console.WriteLine("Fibonacci Term = " + fibonacciTerm);

                firstTerm = secondTerm;
                secondTerm = fibonacciTerm;

                if (fibonacciTerm % 2 == 0)
                {
                    total += fibonacciTerm;
                }
            }

            Console.WriteLine("\nThe sum of the even-valued terms is " + total);

            Console.WriteLine("\nPress any key to continue..");
            Console.ReadKey();
        }
    }
}
